README.md
elem.go
elements.go
elements_test.go
examples/htmx-fiber-form/main.go
utils.go
utils_test.go

Addresses: https://github.com/chasefleming/elem-go/issues/11

Introduce `Node` interface

---

README.md
utils.go
utils_test.go

Switch `Show` to `If`

---

README.md
elements.go
elements_test.go

Add more list elems

---

elements.go
elements_test.go

Add `Link` element

---

attrs/attrs.go
elem.go
elements_test.go

Added support to boolean attributes.
HTML has 24 such attributes, but this package supports only 8 so far.

added support for boolean attributes #48

---

attrs/attrs.go
elem.go

Add missing boolean attrs

---

elem.go
elements.go
elements_test.go

added support for HTML comments #68

---

README.md
attrs/attrs.go
elem.go
elements.go
elements_test.go

Closes Issue #45 
- Updated Readme.md
- Added support in elements.go
```go
// ========== Embedded Content ==========
func Iframe(attrs attrs.Props, children ...Node) *Element{
return NewElement("iframe", attrs, children...)
}
```
- Updated attrs
```go
// IFrame Attributes
Allow = "allow"
AllowFullScreen = "allowfullscreen"
CSP = "csp"
ReferrerPolicy = "referrerpolicy"
Sandbox = "sandbox"
SrcDoc = "srcdoc"
```

Add support for Embedded component - Iframe

---

attrs/utils.go
attrs/utils_test.go

Example usage:
```go
Div(attrs.Props{attrs.DataAttr("theme"): "cupcake"}, Text("foobar"))
// <div data-theme="cupcake">foobar</div>
```
```go
Div(attrs.DataAttrs(map[string]string{"theme": "cupcake", "foobar": "baz"}), Text("foobar"))
// <div data-theme="cupcake" data-foobar="baz">foobar</div>
```

added DataAttr and DataAttrs function

---

README.md
elem.go
elements.go
elements_test.go

Create `Raw` function for Passing HTML

---

README.md
elem.go
elements.go
elements_test.go
utils_test.go

Add `None` Node for Noop Rendering

---

elem.go
elements_test.go

The doctype preamble needs to be emmitted in order to ensure browsers don't switch to legacy/quirks mode rendering.
Fixes: #91

Add doctype preamble to html tag

---

styles/constants.go

As defined at the Mozilla Developer Network: [backdrop-filter](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter).

Add support for the backdrop-filter style

---

htmx/htmx.go

As talked about in #108, added the server side events and websockets extension attributes to the htmx helper pkg.

Add `hx-sse`, `sse-connect`, `sse-swap`, and `ws-connect` to htmx pkg

---

styles/constants.go

I would like to make use of the `font-variant` CSS property in a project of mine, this allows you to (among other things) set a font to be a `small-caps` variant which can add some visual appeal.
I simply added it to `constants.go`.
I also verified it worked by throwing a style onto the H1 element in the `htmx-fiber-todo` example, however I did not commit that change.

Add `font-variant` property to styles

---

elem.go
elements_test.go

Now able to use single quotes as attribute values.
```go
Div(attrs.Props{
"data-values": `'{"quantity": 5}'`,
})
```
```html
<div data-values="'{" quantity": 5}'"></div>
```
```html
<div data-values='{"quantity": 5}'></div>
```
```html
<div data-values="{"quantity": 5}"></div>
```

Add support for single quoted attrs

---

elem.go
elements.go
elements_test.go

Added a new fragment element that is purely for ergonomics, allowing the ability to group elements without adding an extra wrapper element to the DOM. 
I found this to be useful when I have functions that return nodes that need to be merged into the same parent without any element wrapping it.
```go
func TestFragment(t *testing.T) {
expected := `<div><p>0</p><p>1</p><p>2</p><p>3</p><p>4</p></div>`
nodes1 := []Node{
P(nil,
Text("1"),
),
P(nil,
Text("2"),
),
}
nodes2 := []Node{
P(nil,
Text("3"),
),
P(nil,
Text("4"),
),
}
el := Div(nil,
P(nil,
Text("0"),
),
Fragment(nodes1...),
Fragment(nodes2...),
)
actual := el.Render()
assert.Equal(t, expected, actual)
}
```

Add fragment element

---

styles/constants.go
styles/stylemanager.go
styles/stylemanager_test.go

Adds a basic support for CSS pseudo elements, see #143.
Usage:
```golang
compositeClassName := sm.AddCompositeStyle(CompositeStyle{
PseudoElements: map[string]Props{
constants.PseudoBefore: Props{"content": "'[x] '"},
},
})
```

Added support for ::before and ::after CSS pseudo elements

---

attrs/attrs.go

This PR adds support for the [`as`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#as) attribute in `link` tags in case the asset is [preloaded](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload).

Add support for `as` attribute

---

attrs/attrs.go
elem.go

This PR adds support for the [`nomodule`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#nomodule) attribute in `script` tags.

Add support for nomodule attribute

---

examples/htmx-fiber-counter/main.go

The value on initial page load is currently always 0, even if it had already been modified by clicking the increment or decrement buttons. This causes weird behavior when opening the page in multiple tabs.

Fix fiber counter example

---

elem.go
elements.go
elements_test.go
utils.go

`Text()` now escapes HTML5 special characters for safe rendering. `Raw()` is still available if you need to render code without escaping HTML5 elements — for example, if you need non-standard tags. 
Technically, only `&` and `<` need to be escaped, not `>`. I still escape `>` for consistency and the resulting code passes the validator.
I accidentally ran into the problem that elements were not escaped in Text() and learned that there was no difference between Text and Raw nodes.

added content escaping for text nodes
