README.md, elements.go, elements_test.go
=> Add Additional Text Formatting and Structure Elements

elem.go
=> Performance Improvements

utils.go
=> Show should take and return Node type

htmx/htmx.go
=> Add additional htmx attrs

README.md, elements.go, elements_test.go
=> Add semantic sectioning elements

README.md, elements.go, elements_test.go
#31 
I added <i> Element which can be according to the MDN spec.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i
=> Add Support for <i> Element

utils.go
=> Update Style's String Method with strings.Builder

README.md, elements.go, elements_test.go
=> Add table elements

styles/styles.go
added support for additional font and text style properties.
----
#38
=> Updated styles.go with Additional Font & Text Style Properties

attrs/attrs.go
=> Added table attributes

styles/styles.go
=> Added more visual properties

examples/htmx-fiber-todo/main.go
=> Simplify todo app example

README.md
=> Update Readme with Boolean Attrs Mention

attrs/attrs.go, elem.go, elements.go, elements_test.go
=> Add Semantic Text Content Elements

README.md, elements.go, elements_test.go, styles/styles.go
=> Add Style tag support and CSS

styles/utils.go, styles/utils_test.go
=> Add `styles.Merge` for combining styles

attrs/attrs.go
=> Add "step" and "size" to attributes list

attrs/attrs.go
=> Fix Incorrectly Cased Attributes

README.md, attrs/attrs.go, elements.go, elements_test.go
=> Add Optgroup element

elem.go, elements.go
This closes #93 By making the NewElement function private (and updating all usages of this function from NewElement to newElement)
=> Make NewElement function private

examples/htmx-fiber-todo/main.go
ref https://docs.gofiber.io/#zero-allocation
=> bug: fixup use of fiber context values

elements.go, elements_test.go
Added support for the `<sub>`, `<sup>`, `<b>`, `<u>` elements. 
Added tests for each of the above elements.
=> Add missing text content elements

elements.go, elements_test.go
=> add <ruby>, <rt>, <rp> and tests

README.md, elements.go, elements_test.go
=> Add <base> element

elements.go, elements_test.go, styles/README.md, styles/styles.go, styles/styles_test.go
=> Move `styles.CSS` to `elem.CSS`

attrs/README.md, attrs/utils.go, attrs/utils_test.go
=> Create `Merge` method for attributes

styles/README.md, styles/utils.go, styles/utils_test.go
=> Add Style Utilities

styles/utils.go, styles/utils_test.go
=> Functions for time durations
